package models

import (
	"time"

	"github.com/google/uuid"
)

// WorkOrder tracks a single maintenance or repair job from creation to completion.
// Status flow: open → in_progress → completed | cancelled
// Type: "scheduled" when auto-generated from a MaintenanceSchedule; "manual" when created directly.
type WorkOrder struct {
	Base
	OrgRef

	Title       string `gorm:"not null"`
	Description string
	Priority    string `gorm:"not null;default:'medium'"` // low | medium | high | critical
	Status      string `gorm:"not null;default:'open'"`   // open | in_progress | completed | cancelled
	Type        string `gorm:"not null;default:'manual'"` // scheduled | manual

	AssetID uuid.UUID `gorm:"type:uuid;not null;index"`
	Asset   Asset     `gorm:"foreignKey:AssetID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`

	AssignedToID *uuid.UUID `gorm:"type:uuid;index"`
	AssignedTo   *User      `gorm:"foreignKey:AssignedToID;constraint:OnUpdate:CASCADE,OnDelete:SET NULL"`

	CreatedByID uuid.UUID `gorm:"type:uuid;not null"`
	CreatedBy   User      `gorm:"foreignKey:CreatedByID;constraint:OnUpdate:CASCADE,OnDelete:RESTRICT"`

	// Set when auto-generated by a MaintenanceSchedule.
	MaintenanceScheduleID *uuid.UUID           `gorm:"type:uuid;index"`
	MaintenanceSchedule   *MaintenanceSchedule `gorm:"foreignKey:MaintenanceScheduleID;constraint:OnUpdate:CASCADE,OnDelete:SET NULL"`

	DueDate        *time.Time
	CompletedAt    *time.Time
	EstimatedHours *float64
	ActualHours    *float64
	CompletionNotes string

	Photos   []WorkOrderPhoto   `gorm:"foreignKey:WorkOrderID"`
	Comments []WorkOrderComment `gorm:"foreignKey:WorkOrderID"`
}

// WorkOrderPhoto stores a reference to a photo uploaded for a work order.
// Actual files are kept in cloud object storage; only the URL is persisted.
type WorkOrderPhoto struct {
	Base

	WorkOrderID uuid.UUID `gorm:"type:uuid;not null;index"`
	WorkOrder   WorkOrder `gorm:"foreignKey:WorkOrderID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`

	URL      string `gorm:"not null"`
	Filename string `gorm:"not null"`
}

// WorkOrderComment allows managers and admins to annotate a work order.
type WorkOrderComment struct {
	Base

	WorkOrderID uuid.UUID `gorm:"type:uuid;not null;index"`
	WorkOrder   WorkOrder `gorm:"foreignKey:WorkOrderID;constraint:OnUpdate:CASCADE,OnDelete:CASCADE"`

	AuthorID uuid.UUID `gorm:"type:uuid;not null"`
	Author   User      `gorm:"foreignKey:AuthorID;constraint:OnUpdate:CASCADE,OnDelete:RESTRICT"`

	Body string `gorm:"not null"`
}
